### ISSUE TITLE
Adding Test Cases to Test Cycles

### ISSUE THREAD

**Issue by nelsonthedev** [SmartBear/zephyr-scale-server-rest-api-scripts#4]
Hello!

Is there a way to add test cases to test cycles via API in zephyr scale?

@johnathafelix @chicofaccin @otaviomedeirossb @fnmunhoz

**Comment by chicofaccin** [comment]
Hi, @leonardonelson91. 

You can make the POST request to `/testrun` endpoint and include `items` in the body. So a new test cycle will be created, and the test cases will be added to the test cycle.
The body should be something like that:
```
{
  "name": "Full regression",
  "projectKey": "ABC",
    "items": [
          {
              "testCaseKey" : "ABC-T13"
          }
      ]
}
```
I strongly recommend for further questions to use our official support channel: https://smartbear.atlassian.net/servicedesk/customer/portals
